server:
  port: 8081

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PSWD:postgres}
    driver-class-name: org.postgresql.Driver

app:
  temporal:
    host: ${APP_TEMPORAL_HOST:localhost:7233}

flyway:
  user=${POSTGRES_USER:postgres}
  password=${POSTGRES_PSWD:postgres}

rdw:
  request:
    url: http://${RDW_HOST:localhost:8090}/licenseplate-holder
iot:
  request:
    url: http://${IOT_HOST:localhost:8091}/tier-level

logging.level:
  org.springframework.web: INFO
  nl.wlagemaat.demo: DEBUG