server:
  port: 8080

callback:
  url: http://${CLAP_URL:localhost:8081}/licenseplate-holder-response

management:
  server:
    port: 8081
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"