
mq:
  queue:
    vroem: vroem
    vroem.dlq: vroem-dlq
    bas: bas
    worm: worm
    sven: sven
  topic:
    exchange: pre-intake
  routing:
    key:
      pre-intake: pre.intake.#
      vroem: pre.intake.vroem
      bas: pre.intake.bas
      worm: pre.intake.worm
      sven: pre.intake.sven

spring:
  rabbitmq:
    addresses: amqps://rabbit:rabbit@127.0.0.1
    password: rabbit
    username: rabbit
    ssl:
      enabled: false
  sql:
    init:
      platform: postgres
  jpa:
    database: POSTGRESQL
#    hibernate.ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres