
mq:
  queue:
    vroem: vroem
    bas: bas
    worm: worm
    sven: sven
  topic:
    exchange: pre-intake
  routing:
    key:
      pre-intake: pre.intake.#
      vroem: pre.intake.vroem
      bas: pre.intake.bas
      worm: pre.intake.worm
      sven: pre.intake.sven

spring:
  rabbitmq:
    username: rabbit
    password: rabbit
    ssl:
      enabled: false
    host: localhost
    port: 5672
#  sql:
#    init:
#      platform: postgres
  jpa:
    database: POSTGRESQL
#    hibernate.ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

app:
  temporal:
    host: ${APP_TEMPORAL_HOST:localhost:7233}

flyway:
  user=postgres
  password=postgres