server:
  port: 8081

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

app:
  temporal:
    host: ${APP_TEMPORAL_HOST:localhost:7233}

flyway:
  user=postgres
  password=postgres

rdw:
  request:
    url: http://localhost:8090/licenseplate-holder
iot:
  request:
    url: http://localhost:8091/tier-level

logging.level:
  org.springframework.web: INFO
  nl.wlagemaat.demo: DEBUG