version: "3.5"
include:
  - docker-compose-temporal.yml

services:
  apps-db:
    container_name: apps-db
    environment:
      POSTGRES_PASSWORD: insurance
      POSTGRES_USER: insurance
    image: postgres:${POSTGRESQL_VERSION}
    networks:
      - temporal-network
    ports:
      - "5442:5432"
    volumes:
      - /var/lib/postgresql/data
  clap:
    container_name: clap
    depends_on:
      - apps-db
      - temporal-admin-tools
    environment:
      - POSTGRES_USER=insurance
      - POSTGRES_PSWD=insurance
      - POSTGRES_URL=jdbc:postgresql://apps-db:5432/postgres
     #      - POSTGRES_URL=jdbc:postgresql://postgresql:5432/postgres
      - RDW_HOST=rdw:8090
      - IOT_HOST=iot:8091
      - APP_TEMPORAL_HOST=temporal:7233
    image: wlagemaat/clap-app:${CLAP_VERSION}
    restart: on-failure
    networks:
      - temporal-network
    ports:
      - "8081:8081"
  dog:
    container_name: dog
    depends_on:
      - clap
    environment:
      - APP_TEMPORAL_HOST=temporal:7233
    image: wlagemaat/dog-app:${DOG_VERSION}
    restart: on-failure
    networks:
      - temporal-network
  exe:
    container_name: exe
    depends_on:
      - clap
    environment:
      - APP_TEMPORAL_HOST=temporal:7233
    image: wlagemaat/exe-app:${EXE_VERSION}
    restart: on-failure
    networks:
      - temporal-network
  iot:
    container_name: iot
    depends_on:
      - clap
    environment:
      - CLAP_URL=clap:8081
    image: wlagemaat/iot-app:${IOT_VERSION}
    restart: on-failure
    networks:
      - temporal-network
  mass:
    container_name: mass
    depends_on:
      - clap
    environment:
      - APP_TEMPORAL_HOST=temporal:7233
    image: wlagemaat/mass-app:${IOT_VERSION}
    restart: on-failure
    networks:
      - temporal-network
  rdw:
    container_name: rdw
    depends_on:
      - clap
    environment:
      - CLAP_URL=clap:8081
    image: wlagemaat/rdw-app:${IOT_VERSION}
    restart: on-failure
    networks:
      - temporal-network
