version: "3.5"

services:
  apps-db:
    container_name: apps-db
    environment:
      POSTGRES_PASSWORD: insurance
      POSTGRES_USER: insurance
    image: postgres:${POSTGRESQL_VERSION}
    networks:
      temporal-network:
        aliases:
          - apps-db
    ports:
      - "5442:5432"
    volumes:
      - /var/lib/postgresql/data
  rdw:
    container_name: rdw
    environment:
      - CLAP_URL=clap:8080
    image: wvdl/temporal-demo:${RDW_VERSION}
    restart: on-failure
    networks:
      - temporal-network
    ports:
      - "8090:8080"
  iot:
    container_name: iot
    environment:
      - CLAP_URL=clap:8080
    image: wvdl/temporal-demo:${IOT_VERSION}
    restart: on-failure
    networks:
      temporal-network:
        aliases:
          - iot
    ports:
      - "8091:8080"
      - "9091:8081"
  clap:
    container_name: clap
    depends_on:
      - apps-db
    environment:
      - POSTGRES_USER=insurance
      - POSTGRES_PSWD=insurance
      - POSTGRES_URL=jdbc:postgresql://apps-db:5432/postgres
     #      - POSTGRES_URL=jdbc:postgresql://postgresql:5432/postgres
      - RDW_HOST=rdw:8080
      - IOT_HOST=iot:8080
      - APP_TEMPORAL_HOST=${TEMPORAL_HOST}
    image: wvdl/temporal-demo:${CLAP_VERSION}
    restart: on-failure
    networks:
      - temporal-network
    ports:
      - "8081:8080"
      - "9081:8081"
  dog:
    container_name: dog
    depends_on:
      - clap
    environment:
      - APP_TEMPORAL_HOST=${TEMPORAL_HOST}
    image: wvdl/temporal-demo:${DOG_VERSION}
    restart: on-failure
    networks:
      temporal-network:
        aliases:
          - dog
    ports:
      - "8093:8080"
      - "9093:8081"
  exe:
    container_name: exe
    depends_on:
      - clap
    environment:
      - APP_TEMPORAL_HOST=${TEMPORAL_HOST}
    image: wvdl/temporal-demo:${EXE_VERSION}
    restart: on-failure
    networks:
      temporal-network:
        aliases:
          - exe
    ports:
      - "8094:8080"
      - "9094:8081"
  mass:
    container_name: mass
    depends_on:
      - clap
    environment:
      - APP_TEMPORAL_HOST=${TEMPORAL_HOST}
    image: wvdl/temporal-demo:${MASS_VERSION}
    restart: on-failure
    networks:
      temporal-network:
        aliases:
          - mass
    ports:
      - "8092:8080"
      - "9092:8081"

networks:
  temporal-network:
    name: temporal-network
    external: true