###
POST http://localhost:8081/insurance-intake
Accept: application/json
Content-Type: application/json

{
  "validOdds": 95,
  "rdwOdds": 0,
  "rdwTechnicalErrorOdds":  5,
  "isMinorSeverity": false,
  "dogTechnicalErrorOdds": 5,
  "catTechnicalErrorOdds": 5,
  "instantPayoutTechnicalErrorOdds": 5,
  "auditorTechnicalErrorOdds": 5
}

###
POST http://localhost:8090/licenseplate-holder
Accept: application/json
Content-Type: application/json

{
  "licensePlate" : "AA33@@",
  "odds": 10,
  "workflowId":  "1111-2222-3333-4444"
}