app:
  temporal:
    host: ${APP_TEMPORAL_HOST:localhost:7233}

server:
  port: 8082

management:
  server:
    port: 8081
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"